#step 1: build stage 
FROM node:14.16.0-alpine3.13 AS build-stage
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
ENV REACT_APP_API_URL=http://104.248.15.248:3001/api
CMD npm run build

FROM nginx:1.12-alpine
COPY --from=build-stage /app/build /usr/share/nginx/html    
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
